### ISSUE TITLE
Bug? Octoprint UI graph shows just Target bed temperature

### ISSUE THREAD

**Issue by ra100** [tg44/OctoPrint-Prometheus-Exporter#1]
First, thank you for this plugin, I've been thinking about it long time ago, but was lacking some information and enough dedication.

And for the bug, this is what I see, since I installed this. I think it's not desired state, on the other hand, I doesn't bother me much now, when I can see the graph in grafana.

![Screenshot_2019-12-09_22-04-22](https://user-images.githubusercontent.com/3185410/70472714-defe9480-1acf-11ea-8112-7b8026e7b18b.png)

**Comment by tg44** [comment]
This can be the cause of this. I push up a new version, try to force install it pls and report back if it works.

**Comment by tg44** [comment]
auto close, my bad, btw its "live", can you check it?

**Comment by ra100** [comment]
I'll be able to check it tomorrow, I have ~8hrs print time left :) But then, I'll report back.

**Comment by tg44** [comment]
After the update it works! I still waiting for your response, but it is ok on my machine now.

**Comment by ra100** [comment]
I've checked it too, looks fine, thank you.
