### ISSUE TITLE
Grafana Dashboard JSON

### ISSUE THREAD

**Issue by jody90** [tg44/OctoPrint-Prometheus-Exporter#11]
Hi,
really cool Plugin. Thanks for this.
Did you already setup a grafana Dashboard?
It would be great if you could share it.

Thank you
Jody

**Comment by ra100** [comment]
It's not ideal, I have something like this:

[octorpint-grafana.json.zip](https://github.com/tg44/OctoPrint-Prometheus-Exporter/files/4520531/octorpint-grafana.json.zip)
![Screenshot_2020-04-23_08-04-00](https://user-images.githubusercontent.com/3185410/80064763-26466880-8539-11ea-93ee-14a338397e47.png)

**Comment by jody90** [comment]
Thank you very much!

**Comment by tg44** [comment]
ohh sorry, I forgot this... Can either of you PR this to the repo?

**Comment by ra100** [comment]
Sure, if you think this is a good/usable example :) I'll add it.
