### ISSUE TITLE
Enhancement - PrintTime Genius Time Remaining

### ISSUE THREAD

**Issue by tideline3d** [tg44/OctoPrint-Prometheus-Exporter#15]
Would it be possible to publish the time remaining from the Print Time Genius plugin through Prometheus?  Would love to have that on my Grafana dashboard.

**Comment by tg44** [comment]
Based on the docs, not really possible, but I asked it here; https://community.octoprint.org/t/is-remaining-time-available-as-an-event-hook/22579

**Comment by tideline3d** [comment]
No worries if its not possible.  Can probably get that data into Grafana directly through the API.

**Comment by tg44** [comment]
Based on the info I get from `jneilliii` it is possible, I just didn't had time to implement and try it out yet.

**Comment by tg44** [comment]
Can you test this, and report back if it is working for you too?

**Comment by tideline3d** [comment]
Installed now, will follow it with my prints today.  Thanks!
